version: 1.2
workflows:
  - name: ImputationWorkflow
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/Imputation.wdl
  - name: PRScoringWorkflow
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/ScoringPart.wdl
  - name: EndToEndPipeline
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/EndToEndPipeline.wdl
  - name: PerformPopulationPCA
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/PerformPopulationPCA.wdl
  - name: BenchmarkVCFs
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/BenchmarkVCFs.wdl
  - name: CompareBenchmarks
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/CompareBenchmarks.wdl
  - name: BenchmarkAndCompareVCFs
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/BenchmarkAndCompareVCFs.wdl
  - name: SimpleBenchmark
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/SimpleBenchmark.wdl
  - name: ValidateImputation
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/Validation/ValidateImputation.wdl
  - name: ValidateScoring
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/Validation/ValidateScoring.wdl
  - name: FullImputationPRSValidation
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/Validation/FullImputationPRSValidation.wdl
  - name: FindSamplesAndBenchmark
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/FindSamplesAndBenchmark.wdl
  - name: CreateIGVSession
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/CreateIGVSession.wdl
  - name: IndexCramOrBam
    subclass: WDL
    primaryDescriptorPath: /Utilities/IndexCramOrBam.wdl
  - name: BuildHaplotypeMap
    subclass: WDL
    primaryDescriptorPath: /HaplotypeMap/BuildHaplotypeMap.wdl
  - name: FunctionalEquivalence
    subclass: WDL
    primaryDescriptorPath: /FunctionalEquivalence/FunctionalEquivalence.wdl
  - name: PRSWrapper
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/PRSWrapper.wdl
  - name: CKDRiskAdjustment
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/CKDRiskAdjustment.wdl
  - name: CollectBenchmarkSucceeded
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/CollectBenchmarkSucceeded.wdl
  - name: AggregatePRSResults
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/AggregatePRSResults.wdl
  - name: TrainAncestryAdjustmentModel
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/TrainAncestryAdjustmentModel.wdl
  - name: Glimpse1Imputation
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse1Imputation.wdl
  - name: Glimpse2Imputation
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse2Imputation.wdl
  - name: Glimpse2SplitReference
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse2SplitReference.wdl
  - name: Glimpse2MergeBatches
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse2MergeBatches.wdl
  - name: ReduceAndMergeForGlimpse
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/ReduceAndMergeForGlimpse.wdl
  - name: CollectBGEImputationMetrics
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/CollectBGEImputationMetrics.wdl
  - name: Glimpse2ImputationInBatches
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse2ImputationInBatches.wdl
  - name: Glimpse2CheckQC
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse2CheckQC.wdl
  - name: Glimpse2ImputationAndCheckQC
    subclass: WDL
    primaryDescriptorPath: /GlimpseImputationPipeline/Glimpse2ImputationAndCheckQC.wdl
  - name: RNAMetrics
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/RNAMetrics.wdl
  - name: IsoformDiscoveryBenchmark
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/IsoformDiscoveryBenchmark.wdl
  - name: IsoQuant
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/IsoQuant.wdl
  - name: StringTie
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/StringTie.wdl
  - name: Bambu
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/Bambu.wdl
  - name: Flair
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/Flair.wdl
  - name: Talon
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/Talon.wdl
  - name: IsoSeq
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/IsoSeq.wdl
  - name: Flames
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/Flames.wdl
  - name: Cupcake
    subclass: WDL
    primaryDescriptorPath: /LongReadRNABenchmark/Cupcake.wdl
  - name: VcfdistBenchmark
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/VcfdistBenchmark.wdl
  - name: DownsampleAndCollectCoverage
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/DownsampleAndCollectCoverage.wdl
  - name: Dipcall
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/Dipcall.wdl
  - name: ExtractSingleSampleVCFFromCallset
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/ExtractSampleFromVCF.wdl
  - name: MatchFingerprints
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/MatchFingerprints.wdl
  - name: DetectPCANovelties
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/DetectPCANovelties.wdl
  - name: FindSamplesAndSimpleBenchmark
    subclass: WDL
    primaryDescriptorPath: /BenchmarkVCFs/FindSamplesAndSimpleBenchmark.wdl
  - name: PRSQC
    subclass: WDL
    primaryDescriptorPath: /Utilities/WDLs/PRSQC.wdl