version: 1.2
workflows:
  - name: ImputationWorkflow
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/Imputation.wdl
  - name: PRScoringWorkflow
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/ScoringPart.wdl
  - name: EndToEndImputationScoringPipeline
    subclass: WDL
    primaryDescriptorPath: /ImputationPipeline/Scoring