version 1.0

import "cnv_germline_cohort_workflow.wdl" as cnv_germline_cohort
import "single_sample_cnv_germline_case_filter_workflow.wdl" as cnv_germline_case_filter
import "cnv_calling_and_merge_for_fabric.wdl" as cnv_calling_and_merge_for_fabric
workflow CohortCNVCallingAndMergeForFabric {
    input {
        ##################################
      #### required basic arguments ####
      ##################################
      File intervals
      File? blacklist_intervals
      Array[String]+ normal_bams
      Array[String]+ normal_bais
      Array[File]? pon_counts
      String cohort_entity_id
      File contig_ploidy_priors
      Int num_intervals_per_scatter
      File ref_fasta_dict
      File ref_fasta_fai
      File ref_fasta
      String gatk_docker

      ##################################
      #### optional basic arguments ####
      ##################################
      # If true, AnnotateIntervals will be run to create GC annotations and explicit
      # GC correction will be performed by the model generated by
      Boolean? do_explicit_gc_correction
      File? gatk4_jar_override
      Int? preemptible_attempts

      # Required if BAM/CRAM is in a requester pays bucket
      String? gcs_project_for_requester_pays

      ####################################################
      #### optional arguments for PreprocessIntervals ####
      ####################################################
      Int? padding
      Int? bin_length

      ##################################################
      #### optional arguments for AnnotateIntervals ####
      ##################################################
      File? mappability_track_bed
      File? mappability_track_bed_idx
      File? segmental_duplication_track_bed
      File? segmental_duplication_track_bed_idx
      Int? feature_query_lookahead
      Int? mem_gb_for_annotate_intervals

      #################################################
      #### optional arguments for FilterIntervals ####
      ################################################
      File? blacklist_intervals_for_filter_intervals
      Float? minimum_gc_content
      Float? maximum_gc_content
      Float? minimum_mappability
      Float? maximum_mappability
      Float? minimum_segmental_duplication_content
      Float? maximum_segmental_duplication_content
      Int? low_count_filter_count_threshold
      Float? low_count_filter_percentage_of_samples
      Float? extreme_count_filter_minimum_percentile
      Float? extreme_count_filter_maximum_percentile
      Float? extreme_count_filter_percentage_of_samples
      Int? mem_gb_for_filter_intervals

      ##############################################
      #### optional arguments for CollectCounts ####
      ##############################################
      Array[String]? disabled_read_filters_for_collect_counts
      String? collect_counts_format
      Boolean? collect_counts_enable_indexing
      Int? mem_gb_for_collect_counts

      ########################################################################
      #### optional arguments for DetermineGermlineContigPloidyCohortMode ####
      ########################################################################
      Float? ploidy_mean_bias_standard_deviation
      Float? ploidy_mapping_error_rate
      Float? ploidy_global_psi_scale
      Float? ploidy_sample_psi_scale
      Int? mem_gb_for_determine_germline_contig_ploidy
      Int? cpu_for_determine_germline_contig_ploidy

      ############################################################
      #### optional arguments for GermlineCNVCallerCohortMode ####
      ############################################################
      Float? gcnv_p_alt
      Float? gcnv_p_active
      Float? gcnv_cnv_coherence_length
      Float? gcnv_class_coherence_length
      Int? gcnv_max_copy_number
      Int? mem_gb_for_germline_cnv_caller
      Int? cpu_for_germline_cnv_caller

      # optional arguments for germline CNV denoising model
      Int? gcnv_max_bias_factors
      Float? gcnv_mapping_error_rate
      Float? gcnv_interval_psi_scale
      Float? gcnv_sample_psi_scale
      Float? gcnv_depth_correction_tau
      Float? gcnv_log_mean_bias_standard_deviation
      Float? gcnv_init_ard_rel_unexplained_variance
      Int? gcnv_num_gc_bins
      Float? gcnv_gc_curve_standard_deviation
      String? gcnv_copy_number_posterior_expectation_mode
      Boolean? gcnv_enable_bias_factors
      Int? gcnv_active_class_padding_hybrid_mode

      # optional arguments for Hybrid ADVI
      Float? gcnv_learning_rate
      Float? gcnv_adamax_beta_1
      Float? gcnv_adamax_beta_2
      Int? gcnv_log_emission_samples_per_round
      Float? gcnv_log_emission_sampling_median_rel_error
      Int? gcnv_log_emission_sampling_rounds
      Int? gcnv_max_advi_iter_first_epoch
      Int? gcnv_max_advi_iter_subsequent_epochs
      Int? gcnv_min_training_epochs
      Int? gcnv_max_training_epochs
      Float? gcnv_initial_temperature
      Int? gcnv_num_thermal_advi_iters
      Int? gcnv_convergence_snr_averaging_window
      Float? gcnv_convergence_snr_trigger_threshold
      Int? gcnv_convergence_snr_countdown_window
      Int? gcnv_max_calling_iters
      Float? gcnv_caller_update_convergence_threshold
      Float? gcnv_caller_internal_admixing_rate
      Float? gcnv_caller_external_admixing_rate
      Boolean? gcnv_disable_annealing

      ###################################################
      #### arguments for PostprocessGermlineCNVCalls ####
      ###################################################
      Int ref_copy_number_autosomal_contigs
      Int? mem_gb_for_postprocess_germline_cnv_calls
      Int? disk_space_gb_for_postprocess_germline_cnv_calls
      Array[String]? allosomal_contigs

      ##########################
      #### arguments for QC ####
      ##########################
      Int maximum_number_events_per_sample
      Int maximum_number_pass_events_per_sample


      ##################################################################
      #### optional arguments for ExtractPoNFreqAnnotateFilterAndQC ####
      ##################################################################
      Array[String]? filter_expressions #= "QUAL < 50"  # Example filter criteria
      Array[String]? filter_names
      Int? mem_gb_for_extract_pon_freq
      Int? disk_for_extract_pon_freq
      Float? overlap_thresh

      #optional init model
      Array[File]? init_gcnv_model_tars
      File? preprocessed_intervals_for_init_model
      File? filtered_intervals_for_init_model
    }

    call cnv_germline_cohort.CNVGermlineCohortWorkflow {
        input:
            intervals = intervals,
            blacklist_intervals = blacklist_intervals,
            normal_bams = normal_bams,
            normal_bais = normal_bais,
            cohort_entity_id = cohort_entity_id,
            contig_ploidy_priors = contig_ploidy_priors,
            num_intervals_per_scatter = num_intervals_per_scatter,
            ref_fasta_dict = ref_fasta_dict,
            ref_fasta_fai = ref_fasta_fai,
            ref_fasta = ref_fasta,
            gatk_docker = gatk_docker,
            do_explicit_gc_correction = do_explicit_gc_correction,
            gatk4_jar_override = gatk4_jar_override,
            preemptible_attempts = preemptible_attempts,
            gcs_project_for_requester_pays = gcs_project_for_requester_pays,
            padding = padding,
            bin_length = bin_length,
            mappability_track_bed = mappability_track_bed,
            mappability_track_bed_idx = mappability_track_bed_idx,
            segmental_duplication_track_bed = segmental_duplication_track_bed,
            segmental_duplication_track_bed_idx = segmental_duplication_track_bed_idx,
            feature_query_lookahead = feature_query_lookahead,
            mem_gb_for_annotate_intervals = mem_gb_for_annotate_intervals,
            blacklist_intervals_for_filter_intervals = blacklist_intervals_for_filter_intervals,
            minimum_gc_content = minimum_gc_content,
            maximum_gc_content = maximum_gc_content,
            minimum_mappability = minimum_mappability,
            maximum_mappability = maximum_mappability,
            minimum_segmental_duplication_content = minimum_segmental_duplication_content,
            maximum_segmental_duplication_content = maximum_segmental_duplication_content,
            low_count_filter_count_threshold = low_count_filter_count_threshold,
            low_count_filter_percentage_of_samples = low_count_filter_percentage_of_samples,
            extreme_count_filter_minimum_percentile = extreme_count_filter_minimum_percentile,
            extreme_count_filter_maximum_percentile = extreme_count_filter_maximum_percentile,
            extreme_count_filter_percentage_of_samples = extreme_count_filter_percentage_of_samples,
            mem_gb_for_filter_intervals = mem_gb_for_filter_intervals,
            disabled_read_filters_for_collect_counts = disabled_read_filters_for_collect_counts,
            collect_counts_format = collect_counts_format,
            collect_counts_enable_indexing = collect_counts_enable_indexing,
            mem_gb_for_collect_counts = mem_gb_for_collect_counts,
            ploidy_mean_bias_standard_deviation = ploidy_mean_bias_standard_deviation,
            ploidy_mapping_error_rate = ploidy_mapping_error_rate,
            ploidy_global_psi_scale = ploidy_global_psi_scale,
            ploidy_sample_psi_scale = ploidy_sample_psi_scale,
            mem_gb_for_determine_germline_contig_ploidy = mem_gb_for_determine_germline_contig_ploidy,
            cpu_for_determine_germline_contig_ploidy = cpu_for_determine_germline_contig_ploidy,
            gcnv_p_alt = gcnv_p_alt,
            gcnv_p_active = gcnv_p_active,
            gcnv_cnv_coherence_length = gcnv_cnv_coherence_length,
            gcnv_class_coherence_length = gcnv_class_coherence_length,
            gcnv_max_copy_number = gcnv_max_copy_number,
            mem_gb_for_germline_cnv_caller = mem_gb_for_germline_cnv_caller,
            cpu_for_germline_cnv_caller = cpu_for_germline_cnv_caller,
            gcnv_max_bias_factors = gcnv_max_bias_factors,
            gcnv_mapping_error_rate = gcnv_mapping_error_rate,
            gcnv_interval_psi_scale = gcnv_interval_psi_scale,
            gcnv_sample_psi_scale = gcnv_sample_psi_scale,
            gcnv_depth_correction_tau = gcnv_depth_correction_tau,
            gcnv_log_mean_bias_standard_deviation = gcnv_log_mean_bias_standard_deviation,
            gcnv_init_ard_rel_unexplained_variance = gcnv_init_ard_rel_unexplained_variance,
            gcnv_num_gc_bins = gcnv_num_gc_bins,
            gcnv_gc_curve_standard_deviation = gcnv_gc_curve_standard_deviation,
            gcnv_copy_number_posterior_expectation_mode = gcnv_copy_number_posterior_expectation_mode,
            gcnv_enable_bias_factors = gcnv_enable_bias_factors,
            gcnv_active_class_padding_hybrid_mode = gcnv_active_class_padding_hybrid_mode,
            gcnv_learning_rate = gcnv_learning_rate,
            gcnv_adamax_beta_1 = gcnv_adamax_beta_1,
            gcnv_adamax_beta_2 = gcnv_adamax_beta_2,
            gcnv_log_emission_samples_per_round = gcnv_log_emission_samples_per_round,
            gcnv_log_emission_sampling_median_rel_error = gcnv_log_emission_sampling_median_rel_error,
            gcnv_log_emission_sampling_rounds = gcnv_log_emission_sampling_rounds,
            gcnv_max_advi_iter_first_epoch = gcnv_max_advi_iter_first_epoch,
            gcnv_max_advi_iter_subsequent_epochs = gcnv_max_advi_iter_subsequent_epochs,
            gcnv_min_training_epochs = gcnv_min_training_epochs,
            gcnv_max_training_epochs = gcnv_max_training_epochs,
            gcnv_initial_temperature = gcnv_initial_temperature,
            gcnv_num_thermal_advi_iters = gcnv_num_thermal_advi_iters,
            gcnv_convergence_snr_averaging_window = gcnv_convergence_snr_averaging_window,
            gcnv_convergence_snr_trigger_threshold = gcnv_convergence_snr_trigger_threshold,
            gcnv_convergence_snr_countdown_window = gcnv_convergence_snr_countdown_window,
            gcnv_max_calling_iters = gcnv_max_calling_iters,
            gcnv_caller_update_convergence_threshold = gcnv_caller_update_convergence_threshold,
            gcnv_caller_internal_admixing_rate = gcnv_caller_internal_admixing_rate,
            gcnv_caller_external_admixing_rate = gcnv_caller_external_admixing_rate,
            gcnv_disable_annealing = gcnv_disable_annealing,
            ref_copy_number_autosomal_contigs = ref_copy_number_autosomal_contigs,
            mem_gb_for_postprocess_germline_cnv_calls = mem_gb_for_postprocess_germline_cnv_calls,
            disk_space_gb_for_postprocess_germline_cnv_calls = disk_space_gb_for_postprocess_germline_cnv_calls,
            allosomal_contigs = allosomal_contigs,
            maximum_number_events_per_sample = maximum_number_events_per_sample,
            maximum_number_pass_events_per_sample = maximum_number_pass_events_per_sample,
            init_gcnv_model_tars = init_gcnv_model_tars,
            preprocessed_intervals_for_init_model = preprocessed_intervals_for_init_model,
            filtered_intervals_for_init_model = filtered_intervals_for_init_model,
            pon_counts = pon_counts
    }

    scatter (i in range(length(CNVGermlineCohortWorkflow.genotyped_segments_vcfs))) {
        call cnv_germline_case_filter.ExtractPoNFreqAnnotateFilterAndQC {
            input:
                vcf = CNVGermlineCohortWorkflow.genotyped_segments_vcfs[i],
                vcf_idx = CNVGermlineCohortWorkflow.genotyped_segments_vcf_indexes[i],
                panel_vcfs = select_first([CNVGermlineCohortWorkflow.pon_genotyped_segments_vcfs, CNVGermlineCohortWorkflow.genotyped_segments_vcfs]),
                intervals = CNVGermlineCohortWorkflow.preprocessed_intervals,
                overlap_thresh = overlap_thresh,
                filter_expressions = filter_expressions,
                filter_names = filter_names,
                max_events = maximum_number_events_per_sample,
                max_pass_events = maximum_number_pass_events_per_sample,
                sample_name = CNVGermlineCohortWorkflow.read_counts_entity_ids[i],
                mem_gb = mem_gb_for_extract_pon_freq,
                disk_size_gb = disk_for_extract_pon_freq
        }

        Boolean qc_passed_scatter = (ExtractPoNFreqAnnotateFilterAndQC.qc_status == "PASS")

        # call cnv_calling_and_merge_for_fabric.ReformatAndMergeForFabric {
        #     input:
        #         annotated_filtered_vcf = ExtractPoNFreqAnnotateFilterAndQC.annotated_filtered_vcf,
        #         annotated_filtered_vcf_idx = ExtractPoNFreqAnnotateFilterAndQC.annotated_filtered_vcf_idx,
        #         sample_name = CNVGermlineCohortWorkflow.read_counts_entity_ids[i]
        # }

        call cnv_calling_and_merge_for_fabric.GCNVVisualzation {
            input:
            filtered_vcf = ExtractPoNFreqAnnotateFilterAndQC.filtered_vcf,
            case_copy_ratios = CNVGermlineCohortWorkflow.denoised_copy_ratios[i],
            case_read_counts = CNVGermlineCohortWorkflow.read_counts[i],
            panel_copy_ratios = select_first([CNVGermlineCohortWorkflow.pon_denoised_copy_ratios, CNVGermlineCohortWorkflow.denoised_copy_ratios]),
            panel_read_counts = select_first([pon_counts, CNVGermlineCohortWorkflow.read_counts]),
            interval_lists = CNVGermlineCohortWorkflow.sharded_interval_lists
        }
    }

    output {
        Array[File] filtered_cnv_genotyped_segments_vcf = ExtractPoNFreqAnnotateFilterAndQC.filtered_vcf
        Array[File] filtered_cnv_genotyped_segments_vcf_index = ExtractPoNFreqAnnotateFilterAndQC.filtered_vcf_index
        Array[File] filtered_cnv_genotyped_segments_vcf_md5sum = ExtractPoNFreqAnnotateFilterAndQC.filtered_vcf_md5sum

        # File merged_vcf = ReformatAndMergeForFabric.merged_vcf
        # File merged_vcf_index = ReformatAndMergeForFabric.merged_vcf_index
        # File merged_vcf_md5sum = ReformatAndMergeForFabric.merged_vcf_md5sum

        Array[Boolean] qc_passed = qc_passed_scatter
        Array[File] cnv_metrics = ExtractPoNFreqAnnotateFilterAndQC.cnv_metrics
        Array[File] cnv_event_report = GCNVVisualzation.cnv_event_report

    }

}
