FROM rocker/verse:4.4

# Install required LaTeX packages for PDF rendering
RUN tlmgr install booktabs multirow wrapfig float colortbl pdflscape tabu threeparttable threeparttablex ulem makecell xcolor bookmark 
