COVARIATE_X = "Experiment"
SKIP_COMP_HWE = True
MAKE_MISSING_PASS_FILTER = True
EXPERIMENT_ORDER = None
EXPERIMENT_COLORS = None
EXPERIMENT_COLOR_DICT = None
TRUVARI_DUP_TO_INS = True

INCLUDE_QC = False
INCLUDE_TRUVARI = True
INCLUDE_WITTYER = False
