name: 'install-watt'
description: 'installs WATT'
inputs:
  WATT_VERSION:  # id of input
    description: 'WATT tag to use'
    required: true
runs:
  using: "composite"
  steps:
    - name: Clone WATT
      run: git clone -b ${{ inputs.WATT_VERSION }} --depth 1 https://github.com/rickymagner/watt.git ~/watt
      shell: bash
    - name: install requirements
      run: pip install -r ~/watt/requirements.txt
      shell: bash
